

[[servers]]
host = "127.0.0.1"
port = 8080


[[servers]]
host = "127.0.0.1"
port = 8081

[[servers]]
host = "127.0.0.1"
port = 8082

[[servers]]
host = "127.0.0.1"
port = 8083

[[servers]]
host = "127.0.0.1"
port = 8084